"""empty message

Revision ID: ad02ebc5355f
Revises: None
Create Date: 2018-04-06 19:02:41.481711

"""

# revision identifiers, used by Alembic.
revision = 'ad02ebc5355f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=25), nullable=True),
    sa.Column('email', sa.String(length=35), nullable=True),
    sa.Column('password', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_title', sa.String(length=80), nullable=True),
    sa.Column('creator', sa.String(length=25), nullable=True),
    sa.Column('person1', sa.String(length=25), nullable=True),
    sa.Column('person2', sa.String(length=25), nullable=True),
    sa.Column('person3', sa.String(length=25), nullable=True),
    sa.Column('person4', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Comments',
    sa.Column('comment_writer', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('body_comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['Topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('GroupDiscussion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('writer', sa.String(length=50), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('body_discussion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['Group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SubscribedTopic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_sub', sa.String(length=25), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['Topics.id'], ),
    sa.ForeignKeyConstraint(['user_sub'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SubscribedTopic')
    op.drop_table('GroupDiscussion')
    op.drop_table('Comments')
    op.drop_table('Topics')
    op.drop_table('Posts')
    op.drop_table('Group')
    op.drop_table('users')
    op.drop_table('Archive')
    # ### end Alembic commands ###
